import type { HexiumGameState } from "./hexiumTypes";

export const HEXIUM_SAVE_KEY = "hexium_clicker_save_v1";

export const initialHexiumState: HexiumGameState = {
  version: "1.0.0",
  currentScreen: "main_reactor",
  player: {
    id: "guest",
    username: "Guest",
    level: 1,
    xp: 0,
    totalHexMined: 0,
    totalTaps: 0,
    hashrate: 1,
    energy: 100,
    maxEnergy: 100,
    temperature: 0,
    maxTemperature: 100,
  },
  currencies: {
    hex: 0,
    shards: 0,
    premium: 0,
    quantumCores: 0,
    researchPoints: 3,
    corporationCredits: 0,
    warCredits: 0,
  },
  quantumResources: {
    quantumDust: 0,
    voidCrystal: 0,
    singularityCore: 0,
    darkMatter: 0,
    omegaFragment: 0,
  },
  inventory: [
    {
      id: "basic-case",
      name: "Basic Case",
      type: "case",
      tab: "cases",
      rarity: "common",
      amount: 3,
      usable: true,
      equippable: false,
      source: "starter",
      description: "Стартовий кейс HEXIUM Network.",
    },
  ],
  mail: [
    {
      id: "welcome-gift",
      title: "Welcome to HEXIUM Network",
      sender: "HEXIUM SYSTEM",
      status: "unread",
      message: "Твій HEX-CORE активовано. Забери стартовий набір майнера.",
      createdAt: Date.now(),
      rewards: [
        { type: "hex", amount: 3000 },
        { type: "case", caseType: "basic", amount: 1 },
      ],
    },
  ],
  notifications: [
    {
      id: "core-online",
      title: "HEXIUM CORE ONLINE",
      description: "Системи гри підключені до App Core.",
      category: "system",
      priority: "normal",
      read: false,
      createdAt: Date.now(),
      actionScreen: "main_reactor",
    },
  ],
  // All active screens available for navigation.
  unlockedScreens: [
    "main_reactor",
    "hex_bots",
    "shop",
    "cases",
    "tasks",
    "daily_rewards",
    "friends",
    "profile",
    "reactor_modules",
    "black_market",
    "reactor_pets",
    "secret_blueprints",
    "artifacts",
    "expeditions",
    "world_bosses",
    "ascension",
    "battle_pass",
    "research_center",
  ],
  lastSavedAt: Date.now(),
};
